version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: simple_management
    environment:
      POSTGRES_DB: simple_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: